//eCommerce Content:

var ecomChap1 = ["Dimensions of Digital Value Chains",
"eBusiness Categories",
"eCommerce vs eBusiness",
"mCommerce",
"eCommerce Customer Journey",
"Emergence of Digital Value Chains",
"Added Value of Digital Value Chains",
"Classical Supply Chain",
"Value Networks",
"Disintermediation vs Reintermediation",
"Horizontal vs Vertical Marketplaces",
"Agora Business Web",
"Aggregator Business Web",
"Integrator Business Web",
"Alliance Business Web",
"Distributor Business Web"];

var ecomChap2 = ["Business Model vs Plan vs Case",
"Business Model Canvas (Overview)",
"Customer Segments",
"Value Proposition",
"Channels",
"Customer Relationships",
"Revenue Streams",
"Key Resources",
"Key Activities",
"Key Partnerships",
"Cost Structures",
"Business Model Patterns",
"Unbundling Business Models (Pattern #1)",
"Long Tail Business Models (Pattern #2)",
"Multi-sided Platforms (Pattern #3)",
"Free Business Models (Pattern #4)"];

var ecomChap3 = ["Two and Three-Tier-Architectures",
"N-Tier-Architectures",
"Pre-Web and Web Era",
"Blade Systems",
"Centralized vs Distributed Server Architectures",
"Vertical Scaling",
"Horizontal Scaling",
"Capacity Planning",
"Baseline Measurements",
"System Metrics and Load Balancing",
"Scalability Factor",
"Benefits of Load Balancing",
"DNS-based Load Balancing",
"Layer-4-Switching",
"Content Switching",
"Load Balancing Algorithms",
"Cloud Computing Definition",
"Cloud Service Models",
"Five Attributes of Cloud Computing",
"Cloud Deployment Models",
"Supply-Side Economics of Scale",
"Demand-Side Economics of Scale",
"Virtualization Types",
"Hypervisors"];

var ecomChap4 = ["Features of the WWW",
"Web 1.0, 2.0, 3.0",
"XML",
"HTML",
"HTTP Get and Post",
"HTML 5",
"CSS",
"Dynamic Web Pages",
"Client-side Programming",
"Scripting Languages and JavaScript",
"JavaScript Basics",
"AJAX and DOM",
"Ajax Basics",
"Application Programs",
"Server Pages",
"PHP",
"Servlets and Java Server Pages",
"Basic Backend Architecture",
"Model-View-Controller",
"Attracting Customers",
"Engaging Customers",
"Increasing Average Order Value",
"Moment of Purchase",
"Customer Retention",
"Loyalty and Advocacy"];

var ecomChap5 = ["Drivers of eCommerce Security Problems",
"Unintentional Threads",
"Intentional Attacks",
"Network-level Security vs Application-level Security",
"Firewalls",
"Demilitarized Zones",
"Intrusion Detection Systems",
"Authentication & Authorization",
"Auditing & availability",
"Confidentiality, Integrity & Non-repudation",
"Symmetric Encryption",
"Asymmetric Encryption",
"Digital Signature",
"Digital Certificates",
"Certification Authority",
"Secure Socket Layer"];

var ecomChap6 = ["ePayment",
"Payment Cards",
"eCash/Digital Cash",
"Smart Cards",
"eWallets/Digital Wallets",
"Criteria for a Successful ePayment System",
"Types of Cards",
"Stages	of	Credit	Card	Transaction	Processing",
"Actors and Stakeholders",
"Authorization",
"Clearing and Settelment",
"Additional Actors for Online Transactions",
"Options for the Payment Card Value Chain",
"Payment Card Risks",
"Mechanism for Preventing Payment Card Fraud"];

var ecomChap7 = ["Basic Approach",
"Transactions as Double-Entry Bookkeeping",
"A Chain of Transactions",
"Comon Transactions Forms",
"Block Depth & Height",
"Elliptic Curve Multiplication",
"Creation of Bitcoin Adresses",
"Nondeterministic Wallets",
"Deterministic Wallets",
"Mnemonic Code Words",
"Paper Wallets",
"Transactions - Overview",
"Struture of a Transaction",
"Node Types",
"The Bitcoin Network",
"The Blockchain",
"Mining & Consensus"];

var ecomChap8 = ["Publishers & Advertisers",
"Ad Agencies & Ad Networks",
"Ad Network Categories",
"Ad Network Workflow",
"Online Ad Exchange",
"Ad Exchange Workflow",
"Demand/Supply-side Platform",
"Targeted Advertising",
"Targeting Categories",
"Pricing Models",
"Cookies Problem, Solutions and Definition",
"Cookie Types",
"Cookie - Lifecycle",
"3rd Party Cookies",
"Recommender Systems",
"RS - Approaches",
"Conted-based Recommendations",
"Collaborative Filtering",
"Knowlage-based Recommendations"];


var ecomStacks = [];
ecomStacks.push({"title" : "eCommerce and Digital Value Chains", "cards" : ecomChap1});
ecomStacks.push({"title" : "eCommerce Business Models", "cards" : ecomChap2});
ecomStacks.push({"title" : "Infrastructures for eCommerce", "cards" : ecomChap3});
ecomStacks.push({"title" : "eCommerce Web Applications", "cards" : ecomChap4});
ecomStacks.push({"title" : "eCommerce Security", "cards" : ecomChap5});
ecomStacks.push({"title" : "Electronic Payment", "cards" : ecomChap6});
ecomStacks.push({"title" : "Bitcoin", "cards" : ecomChap7});
ecomStacks.push({"title" : "Online Advertising, Marketing and Targeting", "cards" : ecomChap8});

addCourse("eCommerce","eCom",ecomStacks);