
var pvChap6 = ["Growth parameters and properties",
"Properties of thin film",
"Ex-situ vs. in-situ",
"Profilometry",
"Thickness determination",
"Microscopy",
"Scanning electron microscope",
"Atomic force microscope",
"X-ray diffraction",
"Structural analysis of thin films",
"Chemical composition",
"X-ray Photoelectron Spectroscopy",
"Chemical composition",
"Electrical properties",
"Hall effect",
"Optical properties",
"Optics at interfaces: Fresnel coefficients"];

var pvChap7 = ["Growth parameters and properties",
"Properties of thin film",
"Ex-situ vs. in-situ",
"Profilometry",
"Thickness determination",
"Microscopy",
"Scanning electron microscope",
"Atomic force microscope",
"X-ray diffraction",
"Structural analysis of thin films",
"Chemical composition",
"X-ray Photoelectron Spectroscopy",
"Chemical composition",
"Electrical properties",
"Hall effect",
"Optical properties",
"Optics at interfaces: Fresnel coefficients"];

var pvChap7 = ["Electrical properties - Definition of sheet resistance",
"Electrical properties - Measurement of conductivity",
"Electrical properties - 4-point probe",
"Optical properties",
"Optical properties - Fresnel coefficients",
"Optics at interfaces",
"Antireflection coatings",
"What does a thin film spectrum look like?",
"TCOs: why?",
"TCO in thin film solar cells",
"Principal requirements for TCOs",
"Burstein-Moss shift",
"Drude theory of current transport",
"Resistivity of TCOs",
"Optics of TCOs",
"Typical spectrum of a TCO",
"Variation of doping",
"Requirements in thin film solar cells",
"Tin oxide (SnO2)",
"Tin oxide by atmospheric pressure CVD",
"Indium tin oxide (ITO)",
"Application of ITO in FPDs",
"Zinc oxide",
"Key control parameters in TCO fabrication",
"Structure of amorphous silicon",
"Comparison of silicon structures",
"Structure of a-Si:H",
"Staebler-Wronski effect (SWE)"];

var pvChap8 = ["Optics of TCOs", 
"Typical spectrum of a TCO",
"Variation of doping",
"Requirements in thin film solar cells",
"Tin oxide (SnO2)",
"Float glass production",
"Tin oxide by atmospheric pressure CVD",
"Indium tin oxide (ITO)",
"Application of ITO in FPDs",
"Zinc oxide",
"Key control parameters in fabrication",
"Structure of amorphous silicon",
"Comparison of silicon structures",
"Structure of a-Si:H",
"Photoconductivity of a-Si:H",
"Staebler-Wronski effect (SWE)",
"Preparation of a-Si:H",
"Advantages of thin-film amorphous silicon solar cells",
"a-Si:H thin-film solar cells",
"Carrier injection",
"a-Si:H thin-film solar cells",
"Staebler-Wronski effect (SWE) in cells",
"SWE: influence of i-layer thickness",
"a-Si:H thin-film solar cells"];

var pvStacks = [];
pvStacks.push({"title" : "Lecture 6 - Analysis of thin films", "cards": pvChap6});
pvStacks.push({"title" : "Lecture 7 - TCOs & Amorphous", "cards": pvChap7});
pvStacks.push({"title" : "Lecture 8 - TCOs & Amorphous", "cards": pvChap8});

addCourse("Dünnenschichtphotovoltaik und neue Konzepte","PV2",pvStacks);